language: c
compiler:
  - cc
script: 
  - cmake --version
  - cd src

  - cd Jacobi_OMP
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./deepflow2 -h
  - cd ../..

  - cd Jacobi_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./deepflow2 -h
  - cd ../..

  - cd RBSOR_OMP
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./deepflow2 -h
  - cd ../..

  - cd RBSOR_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./deepflow2 -h
  - cd ../..

  - cd SOR_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./deepflow2 -h
  - cd ../..

  - cd 'SOR_serial_optimized_(original_implementation)'
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./deepflow2 -h
  - cd ../..
