language: c
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcr-dev
      - libmpich-dev
      - mpich
      - mpich-doc
      - npm
      - libopencv-dev
      - python-opencv
before_script:
  - "npm install -g markdown-link-check"
script:
  - cmake --version
  - mpiexec --version
  - markdown-link-check application/README.md
  - markdown-link-check application/slowmo_guide.md
  - markdown-link-check application/stylize_guide.md
  
  # test compiling tools
  - cd tools
  - cd flo_visualization
  - cd imageLib
  - make
  - cd ..
  - make
  - ls
  - cp color_flow ../../
  - cd ..
  - cd flo2svflow
  - make
  - ls
  - cp converter ../../
  - cd ../..
  
  - cd src
  - wget "https://github.com/zeruniverse/CS205-project/releases/download/0.01/ak1.ppm"
  - wget "https://github.com/zeruniverse/CS205-project/releases/download/0.01/ak2.ppm"
  - wget "https://github.com/zeruniverse/CS205-project/releases/download/0.01/ak_forward.match"
  
  # test implementations
  - cd RBSOR_MPI
  - bash compile_mpi.sh
  - cd build
  # Don't test MPI in travis-ci, it's evil (You must have multiple CPUs to run MPI version... Travis-ci will stuck.)
  # - time mpirun -np 2 ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  #- ls -lh out.flo
  - cd ../..

  - cd RBSOR_MPI_OMP
  - bash compile_mpi.sh
  - cd build
  # Don't test MPI in travis-ci, it's evil (You must have multiple CPUs to run MPI version... Travis-ci will stuck.)
  # - time mpirun -np 2 ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  #- ls -lh out.flo
  - cd ../..
 
  - cd Jacobi_OMP
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..

  - cd Jacobi_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cp out.flo ../../../
  - cd ../..

  - cd RBSOR_OMP
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cp out.flo ../../../
  - cd ../..

  - cd RBSOR_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..

  - cd SOR_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..

  - cd 'SOR_serial_optimized_(original_implementation)'
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..
  
  # test tools on flow
  - cd ..
  - ls
  - ./color_flow out.flo out.png
  - ./converter out.flo output.sVflow
  - ls -lh
  
  - echo "Done!"
