language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cd src
  - wget "https://github.com/zeruniverse/CS205-project/releases/download/0.01/ak1.ppm"
  - wget "https://github.com/zeruniverse/CS205-project/releases/download/0.01/ak2.ppm"
  - wget "https://github.com/zeruniverse/CS205-project/releases/download/0.01/ak_forward.match"
  
  - cd Jacobi_OMP
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..

  - cd Jacobi_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..

  - cd RBSOR_OMP
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..

  - cd RBSOR_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..

  - cd SOR_serial
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..

  - cd 'SOR_serial_optimized_(original_implementation)'
  - mkdir build
  - cd build
  - cmake ..
  - make
  - time ./deepflow2 ../../ak1.ppm ../../ak1.ppm out.flo -match ../../ak_forward.match
  - ls -lh out.flo
  - cd ../..
